services:
  web:
    build: .
    ports: 
      - 5000:5000
      - 9229:9229 # <- debugging 
    volumes:
      - .:/user/src/app
      - /user/src/app/node_modules
    command: yarn dev
    environment:
      PORT: 5000
